bookproject/bookproject/bookapp/urls.py
from django.urls import path

from .import views
app_name='bookapp'


urlpatterns = [
  path('',views.index,name='index'),
  path('book/<int:book_id>/',views.detail,name='detail'),
  path('add/',views.add,name='add'),
  path('update/<int:id>/',views.update,name='update'),
  path('delete/<int:id>/',views.delete,name='delete'),

]

bookproject/bookproject/bookproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bookapp.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bookproject/bookproject/bookapp/models.py
from django.db import models

# Create your models here.
class Books(models.Model):
    name=models.CharField(max_length=250)
    img=models.ImageField(upload_to='pics')
    year=models.IntegerField()
    price=models.IntegerField()

    def __str__(self):
        return self.name

bookproject/bookproject/bookapp/forms.py
from django import forms
from . models import Books

class BooksForm(forms.ModelForm):
    class Meta:
        model=Books
        fields=['name','year','price','img']

bookproject/bookproject/bookapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Books
from .forms import BooksForm

# Create your views here.
def index(request):
    book=Books.objects.all()
    context={
      'book_list':book
     }
    return render(request,'index.html',context)
def detail(request,book_id):
    book=Books.objects.get(id=book_id)
    return render(request,'detail.html',{'book':book})

def add(request):
    if request.method=='POST':
        name=request.POST.get('name')
        year=request.POST.get('year')
        price=request.POST.get('price')
        img=request.FILES['img']
        book=Books(name=name,year=year,price=price,img=img)
        book.save()
    return render(request,'add.html')
def update(request,id):
    book=Books.objects.get(id=id)
    form=BooksForm(request.POST or None,request.FILES,instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form,'book':book})

def delete(request,id):
    if request.method=='POST':
        book=Books.objects.get(id=id)
        book.delete()
        return redirect('/')
    return render(request,'delete.html')

bookproject/bookproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="enter book name"><br>
   <input type="text" name="year" placeholder="enter book year"><br>
   <input type="number" name="price" placeholder="enter book price"><br>
   <input type="file" name="img"><br>
   <input type="submit">
</form>
{% endblock %}

bookproject/bookproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}" >
</head>
<body>

<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      <i><b>ONLINE BOOK STORE</b></i>
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

bookproject/bookproject/templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you want to delete this book?
    <input type="submit">
</form>

bookproject/bookproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
           <img src="{{book.img.url}}" style="width:400px;height:400px;padding:10px;">
        </div>
<div>

    <h3> {{book.name}}</h3>
    <h4>{{book.price}}</h4>
    <h5> {{book.year}}</h5>

<a class="btn btn-warning" href="{% url 'bookapp:update' book.id %}"> update </a>
<a class="btn btn-danger" href="{% url 'bookapp:delete' book.id %}">delete</a>
</div>
    </div>
</div>
{% endblock %}

bookproject/bookproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<nav class="btn btn-warning">
<a href="{% url 'bookapp:add' %}">add book</a>
</nav>
<div class="container">
 <div class="row">
  {% for i in book_list %}
  <div class="col-md-4">
   <div class="card" style="width:300px;margin:10px;">
    <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="200" height="150">
       <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url 'bookapp:detail' i.id %}" class="btn btn-primary">Go details</a>
  </div>
</div>
  </div>
   {% endfor %}

 </div>
</div>





{% endblock %}

bookproject/bookproject/templates/update.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
{% endblock %}